"""Core domain abstractions, states, events, and FSM engine."""

from auto_pr.core.states import (
    WorkflowState,
    DomainEvent,
    VALID_TRANSITIONS,
    TERMINAL_STATES,
)
from auto_pr.core.events import WorkflowEventPayload
from auto_pr.core.models import (
    AgentPermissionScope,
    UNDERSTANDING_AGENT_PERMISSIONS,
    CONTEXT_COMPILER_PERMISSIONS,
    IMPLEMENTATION_AGENT_PERMISSIONS,
    DEBUGGING_AGENT_PERMISSIONS,
    QUALITY_GATE_PERMISSIONS,
    WorkItemInput,
    WorkItemSpec,
    AmbiguityChecklist,
    AcceptanceCriterion,
    FileExtract,
    ContextPack,
    FilePatch,
    ChangeSet,
    ValidationCommandResult,
    ValidationRun,
    DebugHypothesis,
    HumanInterventionRequest,
    HumanGuidance,
    CriterionVerification,
    DiffRiskAnalysis,
    QualityGateReport,
    PullRequestInfo,
)
from auto_pr.core.fsm import (
    DeterministicFSM,
    InvalidStateTransitionError,
    GuardConditionFailedError,
)

__all__ = [
    "WorkflowState",
    "DomainEvent",
    "VALID_TRANSITIONS",
    "TERMINAL_STATES",
    "WorkflowEventPayload",
    "AgentPermissionScope",
    "UNDERSTANDING_AGENT_PERMISSIONS",
    "CONTEXT_COMPILER_PERMISSIONS",
    "IMPLEMENTATION_AGENT_PERMISSIONS",
    "DEBUGGING_AGENT_PERMISSIONS",
    "QUALITY_GATE_PERMISSIONS",
    "WorkItemInput",
    "WorkItemSpec",
    "AmbiguityChecklist",
    "AcceptanceCriterion",
    "FileExtract",
    "ContextPack",
    "FilePatch",
    "ChangeSet",
    "ValidationCommandResult",
    "ValidationRun",
    "DebugHypothesis",
    "HumanInterventionRequest",
    "HumanGuidance",
    "CriterionVerification",
    "DiffRiskAnalysis",
    "QualityGateReport",
    "PullRequestInfo",
    "DeterministicFSM",
    "InvalidStateTransitionError",
    "GuardConditionFailedError",
]
